[package]
name = "rftp"
version = "0.1.1"
authors = ["Ellis Hoag <ellis.sparky.hoag@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Download and upload files from a server via sftp."
readme = "README.md"
keywords = ["sftp", "ssh", "scp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ssh2 = { version = "0.1", git = "https://github.com/spebern/async-ssh2.git", branch = "tokio-stream"}
clap = "2.33.0"
tokio = { version = "0.2", git = "https://github.com/spebern/tokio", features = ["full"] }
tui = "0.8.0"
termion = "1.5.5"
textwrap = "0.11.0"
