[package]
name = "rftp"
version = "0.1.3"
authors = ["Ellis Hoag <ellis.sparky.hoag@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Download and upload files from a server via sftp."
readme = "README.md"
keywords = ["sftp", "ssh", "scp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8.0"
clap = "2.33.0"
tui = "0.8.0"
termion = "1.5.5"
textwrap = "0.11.0"
dirs = "2.0.2"
crossbeam-channel = "0.4.2"
