[package]
name = "rftp"
version = "0.1.0"
authors = ["Ellis Hoag <ellis.sparky.hoag@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Download and upload files from a server via sftp."
readme = "README.md"
keywords = ["sftp", "ssh", "scp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8.0"
clap = "2.33.0"
tokio = { version = "0.2", features = ["rt-core", "rt-threaded", "time", "sync", "fs", "macros"] }
tui = "0.8.0"
termion = "1.5.5"
